### PR TITLE
explain with respect to a Wiki

### PR DESCRIPTION
**Pull request by gregwebs**

### CODE REVIEW

**Comment by snoyberg** [comment]
Is it also worth mentioning that it's easier to develop tooling around Github+Markdown?

**Comment by gregwebs** [comment]
sure, but I think gitit is already git stored markdown

**Comment by snoyberg** [comment]
One of the things I want to make clear about goals here is that we want the data to be easily reused in other contexts. I would consider tying in to a bunch of Wiki-specific features a bad thing, because that could hinder the ability of someone generating a PDF, for example. In my mind, the simplicity of "a directory full of Markdown" is a feature in and of itself.

**Comment by gregwebs** [comment]
sure, but gitit content may also be stored as a directory full of markdown.

**Pull request merged**
