### PR TITLE
add list of basic transformers

### PR DESCRIPTION
**Pull request by levinotik**
I just wanted to kick things off with this pull request because I've found even the small amount of material here to be quite helpful. 

Really wasn't sure about the formatting (if the various sections laid out should be linking to a separate doc, etc) or even exactly what the basic transformers content was meant to cover. 

Again, just wanted to kick things off to get some feedback. Thank you.

### CODE REVIEW

**Comment by snoyberg** [comment]
Thanks!

**Comment by levinotik** [comment]
Thank you. 

I'm particularly interested in this area because I think there aren't sufficient walkthroughs of the general concept and, perhaps more importantly for an intermediate Haskeller, an overview of the various libraries in the ecosystem. 

For the section on example usage, should it rely on the transformers package or should the examples not rely on any particular package?

**Comment by snoyberg** [comment]
I'd recommend using the transformers package. We should stick to commonly
held best practices whenever possible.

**Comment by levinotik** [comment]
That makes sense. Part of the very problem is that it isn't immediately obvious when you start writing actual projects what the standards are for transformers and how the different libraries fit together. 

I'll work on basic example usages with transformers. 

Thank you

**Comment by snoyberg** [comment]
Awesome, look forward to it

**Pull request merged**
