### PR TITLE
Added exercises from https://github.com/tobiasgwaaler/hands-on-haskell

### PR DESCRIPTION
**Pull request by tobiasgwaaler**
The collection of topics may seem a bit arbitrary, but it's a starting point :)

### CODE REVIEW

**Comment by psibi** [comment]
:+1: It would be nice if you can hyperlink the exercise code from `exercises/README.md` file.

**Comment by snoyberg** [comment]
Thank you! I've also given you commit access to make any further tweaks you'd like to this.

**Comment by tobiasgwaaler** [comment]
Great, thank you :)

**Comment by tobiasgwaaler** [comment]
@psibi good point! I've added hyperlinks just now

**Comment by psibi** [comment]
@tobiasgwaaler Thanks!

**Pull request merged**
